/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;
import java.util.Iterator;
import javax.swing.JOptionPane;
import model.Vitals;
import model.VitalsDirectory;
import model.Encounter;
import model.Person;
import model.PersonDirectory;

/**
 *
 * @author shubhampatil
 */
public class AddVitalsPanel extends javax.swing.JPanel {

    /**
     * Creates new form AddVitalsPanel
     */
    VitalsDirectory vdirectory;
    Encounter ehistory;
    PersonDirectory directory;
    
    public AddVitalsPanel(VitalsDirectory vdirectory, PersonDirectory directory, Encounter ehistory) {
        initComponents();
        this.vdirectory =  vdirectory;
        this.directory = directory;
        this.ehistory = ehistory;
        populateComboBox();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblAddVitals = new javax.swing.JLabel();
        lblHeartRate = new javax.swing.JLabel();
        lblBloodPressure = new javax.swing.JLabel();
        lblBloodOxygenLevel = new javax.swing.JLabel();
        lblGlucoseLevel = new javax.swing.JLabel();
        lblCholestrolLevel = new javax.swing.JLabel();
        txtHeartRate = new javax.swing.JTextField();
        txtDystolic = new javax.swing.JTextField();
        txtBloodOxygenLevel = new javax.swing.JTextField();
        txtGlucoseLevel = new javax.swing.JTextField();
        txtCholestrolLevel = new javax.swing.JTextField();
        lblDystolic = new javax.swing.JLabel();
        lblSystolic = new javax.swing.JLabel();
        txtSystolic = new javax.swing.JTextField();
        btnSaveVitals = new javax.swing.JButton();
        cmbBoxName = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblAddVitals.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        lblAddVitals.setText("Add Vitals");
        add(lblAddVitals, new org.netbeans.lib.awtextra.AbsoluteConstraints(419, 41, 109, -1));

        lblHeartRate.setText("Heart Rate:");
        add(lblHeartRate, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 121, -1, -1));

        lblBloodPressure.setText("Blood Pressure:");
        add(lblBloodPressure, new org.netbeans.lib.awtextra.AbsoluteConstraints(313, 159, -1, -1));

        lblBloodOxygenLevel.setText("Blood Oxyegn Level:");
        add(lblBloodOxygenLevel, new org.netbeans.lib.awtextra.AbsoluteConstraints(282, 235, -1, -1));

        lblGlucoseLevel.setText("Glucose Level:");
        add(lblGlucoseLevel, new org.netbeans.lib.awtextra.AbsoluteConstraints(319, 279, -1, -1));

        lblCholestrolLevel.setText("Cholestrol Level:");
        add(lblCholestrolLevel, new org.netbeans.lib.awtextra.AbsoluteConstraints(304, 323, -1, -1));

        txtHeartRate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHeartRateActionPerformed(evt);
            }
        });
        add(txtHeartRate, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 116, 94, -1));

        txtDystolic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDystolicActionPerformed(evt);
            }
        });
        add(txtDystolic, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 154, 94, -1));

        txtBloodOxygenLevel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBloodOxygenLevelActionPerformed(evt);
            }
        });
        add(txtBloodOxygenLevel, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 230, 94, -1));

        txtGlucoseLevel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGlucoseLevelActionPerformed(evt);
            }
        });
        add(txtGlucoseLevel, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 274, 94, -1));

        txtCholestrolLevel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCholestrolLevelActionPerformed(evt);
            }
        });
        add(txtCholestrolLevel, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 318, 94, -1));

        lblDystolic.setText("Dystolic:");
        add(lblDystolic, new org.netbeans.lib.awtextra.AbsoluteConstraints(472, 159, -1, -1));

        lblSystolic.setText("Systolic:");
        add(lblSystolic, new org.netbeans.lib.awtextra.AbsoluteConstraints(469, 197, -1, -1));

        txtSystolic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSystolicActionPerformed(evt);
            }
        });
        add(txtSystolic, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 192, 94, -1));

        btnSaveVitals.setText("Save Vitals");
        btnSaveVitals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveVitalsActionPerformed(evt);
            }
        });
        add(btnSaveVitals, new org.netbeans.lib.awtextra.AbsoluteConstraints(419, 356, -1, -1));

        cmbBoxName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbBoxNameActionPerformed(evt);
            }
        });
        add(cmbBoxName, new org.netbeans.lib.awtextra.AbsoluteConstraints(704, 66, -1, -1));

        jLabel1.setText("Id");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 46, -1, -1));

        jLabel2.setText("Normal Range ");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 90, 120, 20));

        jLabel3.setText(" 50-120");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 160, 130, -1));

        jLabel5.setText(" 50-120");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 120, 130, -1));

        jLabel6.setText("80-140");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 200, -1, -1));

        jLabel7.setText("<85");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 240, -1, -1));

        jLabel8.setText("<200");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 320, -1, -1));

        jLabel9.setText("<100");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 280, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void txtHeartRateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHeartRateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHeartRateActionPerformed

    private void txtDystolicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDystolicActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDystolicActionPerformed

    private void txtBloodOxygenLevelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBloodOxygenLevelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBloodOxygenLevelActionPerformed

    private void txtGlucoseLevelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGlucoseLevelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGlucoseLevelActionPerformed

    private void txtCholestrolLevelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCholestrolLevelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCholestrolLevelActionPerformed

    private void txtSystolicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSystolicActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSystolicActionPerformed

    private void btnSaveVitalsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveVitalsActionPerformed
        // TODO add your handling code here:
        if(txtHeartRate.getText().equals("")){
            
            JOptionPane.showMessageDialog(this, "Please enter your Heart Rate");
        }
        else if(txtDystolic.getText().equals("")){
            
            JOptionPane.showMessageDialog(this, "Please enter your Dystolic Blood Pressure");
        }
        
        else if(txtSystolic.getText().equals("")){
            
            JOptionPane.showMessageDialog(this, "Please enter your Systolic Blood Pressure");
        }
        
        else if(txtBloodOxygenLevel.getText().equals("")){
            
            JOptionPane.showMessageDialog(this, "Please enter your Blood Oxygen Level");
        }
        
        else if(txtGlucoseLevel.getText().equals("")){
            
            JOptionPane.showMessageDialog(this, "Please enter your Glucose Level");
        }
        
        else if(txtCholestrolLevel.getText().equals("")){
            
            JOptionPane.showMessageDialog(this, "Please enter your Cholestrol Level");
        }
        else{
        addnewvitals();
        JOptionPane.showMessageDialog(this, "Vitals have been saved");
        
        txtHeartRate.setText("");
        txtDystolic.setText("");
        txtSystolic.setText("");
        txtBloodOxygenLevel.setText("");
        txtGlucoseLevel.setText("");
        txtCholestrolLevel.setText("");
        }
    }//GEN-LAST:event_btnSaveVitalsActionPerformed

    private void cmbBoxNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbBoxNameActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_cmbBoxNameActionPerformed

    public void addnewvitals(){
        int HeartRate = Integer.parseInt(txtHeartRate.getText());
        double Dystolic = Double.parseDouble(txtDystolic.getText());
        double Systolic = Double.parseDouble(txtSystolic.getText());
        int BloodOxygen = Integer.parseInt(txtBloodOxygenLevel.getText());
        double Glucose = Double.parseDouble(txtGlucoseLevel.getText());
        double Cholestrol = Double.parseDouble(txtCholestrolLevel.getText());
        
        Vitals vr = vdirectory.addNewVitals();
        ehistory.AddEncounter(Integer.parseInt(cmbBoxName.getSelectedItem().toString()), vr);
        
        vr.setHeartRate(HeartRate);
        vr.setDystolic(Dystolic);
        vr.setSystolic(Systolic);
        vr.setBloodOxygen(BloodOxygen);
        vr.setGlucose(Glucose);
        vr.setCholestrol(Cholestrol);
        vr.setTimeStamp();
        
    }
    public void populateComboBox() {
        
        for( int i=0; i < directory.getDirectory().size(); i++){
             Person pr = new Person();
             pr = directory.getDirectory().get(i);
             String ID = String.valueOf(pr.getId());
             cmbBoxName.addItem(ID);

          
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSaveVitals;
    private javax.swing.JComboBox<String> cmbBoxName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblAddVitals;
    private javax.swing.JLabel lblBloodOxygenLevel;
    private javax.swing.JLabel lblBloodPressure;
    private javax.swing.JLabel lblCholestrolLevel;
    private javax.swing.JLabel lblDystolic;
    private javax.swing.JLabel lblGlucoseLevel;
    private javax.swing.JLabel lblHeartRate;
    private javax.swing.JLabel lblSystolic;
    private javax.swing.JTextField txtBloodOxygenLevel;
    private javax.swing.JTextField txtCholestrolLevel;
    private javax.swing.JTextField txtDystolic;
    private javax.swing.JTextField txtGlucoseLevel;
    private javax.swing.JTextField txtHeartRate;
    private javax.swing.JTextField txtSystolic;
    // End of variables declaration//GEN-END:variables
}
