/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;
import java.util.Iterator;
import javax.swing.JOptionPane;
import model.Vitals;
import model.VitalsDirectory;
import model.Encounter;
import model.Person;
import model.PersonDirectory;

/**
 *
 * @author shubhampatil
 */
public class AddVitalsPanel extends javax.swing.JPanel {

    /**
     * Creates new form AddVitalsPanel
     */
    VitalsDirectory vdirectory;
    Encounter ehistory;
    PersonDirectory directory;
    
    public AddVitalsPanel(VitalsDirectory vdirectory, PersonDirectory directory, Encounter ehistory) {
        initComponents();
        this.vdirectory =  vdirectory;
        this.directory = directory;
        this.ehistory = ehistory;
        populateComboBox();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblAddVitals = new javax.swing.JLabel();
        lblHeartRate = new javax.swing.JLabel();
        lblBloodPressure = new javax.swing.JLabel();
        lblBloodOxygenLevel = new javax.swing.JLabel();
        lblGlucoseLevel = new javax.swing.JLabel();
        lblCholestrolLevel = new javax.swing.JLabel();
        txtHeartRate = new javax.swing.JTextField();
        txtDystolic = new javax.swing.JTextField();
        txtBloodOxygenLevel = new javax.swing.JTextField();
        txtGlucoseLevel = new javax.swing.JTextField();
        txtCholestrolLevel = new javax.swing.JTextField();
        lblDystolic = new javax.swing.JLabel();
        lblSystolic = new javax.swing.JLabel();
        txtSystolic = new javax.swing.JTextField();
        btnSaveVitals = new javax.swing.JButton();
        cmbBoxName = new javax.swing.JComboBox<>();

        lblAddVitals.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        lblAddVitals.setText("Add Vitals");

        lblHeartRate.setText("Heart Rate:");

        lblBloodPressure.setText("Blood Pressure:");

        lblBloodOxygenLevel.setText("Blood Oxyegn Level:");

        lblGlucoseLevel.setText("Glucose Level:");

        lblCholestrolLevel.setText("Cholestrol Level:");

        txtHeartRate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHeartRateActionPerformed(evt);
            }
        });

        txtDystolic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDystolicActionPerformed(evt);
            }
        });

        txtBloodOxygenLevel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBloodOxygenLevelActionPerformed(evt);
            }
        });

        txtGlucoseLevel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGlucoseLevelActionPerformed(evt);
            }
        });

        txtCholestrolLevel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCholestrolLevelActionPerformed(evt);
            }
        });

        lblDystolic.setText("Dystolic:");

        lblSystolic.setText("Systolic:");

        txtSystolic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSystolicActionPerformed(evt);
            }
        });

        btnSaveVitals.setText("Save Vitals");
        btnSaveVitals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveVitalsActionPerformed(evt);
            }
        });

        cmbBoxName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbBoxNameActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(282, 282, 282)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblHeartRate)
                            .addComponent(lblBloodOxygenLevel)
                            .addComponent(lblGlucoseLevel)
                            .addComponent(lblCholestrolLevel)
                            .addComponent(lblBloodPressure))
                        .addGap(60, 60, 60)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtHeartRate, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtBloodOxygenLevel, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtGlucoseLevel, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCholestrolLevel, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(lblDystolic)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtDystolic, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblSystolic)
                                .addGap(18, 18, 18)
                                .addComponent(txtSystolic, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnSaveVitals)
                            .addComponent(lblAddVitals, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(104, 104, 104)))
                .addContainerGap(162, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cmbBoxName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(lblAddVitals)
                .addGap(3, 3, 3)
                .addComponent(cmbBoxName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHeartRate)
                    .addComponent(txtHeartRate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDystolic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDystolic)
                    .addComponent(lblBloodPressure))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSystolic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSystolic))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBloodOxygenLevel)
                    .addComponent(txtBloodOxygenLevel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGlucoseLevel)
                    .addComponent(txtGlucoseLevel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCholestrolLevel)
                    .addComponent(txtCholestrolLevel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSaveVitals)
                .addContainerGap(113, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtHeartRateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHeartRateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHeartRateActionPerformed

    private void txtDystolicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDystolicActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDystolicActionPerformed

    private void txtBloodOxygenLevelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBloodOxygenLevelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBloodOxygenLevelActionPerformed

    private void txtGlucoseLevelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGlucoseLevelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGlucoseLevelActionPerformed

    private void txtCholestrolLevelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCholestrolLevelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCholestrolLevelActionPerformed

    private void txtSystolicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSystolicActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSystolicActionPerformed

    private void btnSaveVitalsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveVitalsActionPerformed
        // TODO add your handling code here:
        
        int HeartRate = Integer.parseInt(txtHeartRate.getText());
        double Dystolic = Double.parseDouble(txtDystolic.getText());
        double Systolic = Double.parseDouble(txtSystolic.getText());
        int BloodOxygen = Integer.parseInt(txtBloodOxygenLevel.getText());
        double Glucose = Double.parseDouble(txtGlucoseLevel.getText());
        double Cholestrol = Double.parseDouble(txtCholestrolLevel.getText());
        
        Vitals vr = vdirectory.addNewVitals();
        ehistory.AddEncounter(Integer.parseInt(cmbBoxName.getSelectedItem().toString()), vr);
        
        vr.setHeartRate(HeartRate);
        vr.setDystolic(Dystolic);
        vr.setSystolic(Systolic);
        vr.setBloodOxygen(BloodOxygen);
        vr.setGlucose(Glucose);
        vr.setCholestrol(Cholestrol);
        vr.setTimeStamp();
        JOptionPane.showMessageDialog(this, "Vitals have been saved");
        
    }//GEN-LAST:event_btnSaveVitalsActionPerformed

    private void cmbBoxNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbBoxNameActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_cmbBoxNameActionPerformed

    
    public void populateComboBox() {
        
        for( int i=0; i < directory.getDirectory().size(); i++){
             Person pr = new Person();
             pr = directory.getDirectory().get(i);
             String ID = String.valueOf(pr.getId());
             cmbBoxName.addItem(ID);

          
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSaveVitals;
    private javax.swing.JComboBox<String> cmbBoxName;
    private javax.swing.JLabel lblAddVitals;
    private javax.swing.JLabel lblBloodOxygenLevel;
    private javax.swing.JLabel lblBloodPressure;
    private javax.swing.JLabel lblCholestrolLevel;
    private javax.swing.JLabel lblDystolic;
    private javax.swing.JLabel lblGlucoseLevel;
    private javax.swing.JLabel lblHeartRate;
    private javax.swing.JLabel lblSystolic;
    private javax.swing.JTextField txtBloodOxygenLevel;
    private javax.swing.JTextField txtCholestrolLevel;
    private javax.swing.JTextField txtDystolic;
    private javax.swing.JTextField txtGlucoseLevel;
    private javax.swing.JTextField txtHeartRate;
    private javax.swing.JTextField txtSystolic;
    // End of variables declaration//GEN-END:variables
}
