/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import model.Person;
import model.PersonDirectory;
import javax.swing.JOptionPane;
/**
 *
 * @author shubhampatil
 */


public class PersonPanel extends javax.swing.JPanel {

    /**
     * Creates new form PersonPanel
     */
    PersonDirectory directory;
    public PersonPanel(PersonDirectory directory) {
        initComponents();
        
        this.directory = directory;
       
    }

    PersonPanel() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblHeading = new javax.swing.JLabel();
        lblPersonName = new javax.swing.JLabel();
        lblphone = new javax.swing.JLabel();
        lblHeight = new javax.swing.JLabel();
        lblWeight = new javax.swing.JLabel();
        lblHouseNo = new javax.swing.JLabel();
        lblCommunity = new javax.swing.JLabel();
        lblCity = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtPhone = new javax.swing.JTextField();
        txtHeight = new javax.swing.JTextField();
        txtWeight = new javax.swing.JTextField();
        txtHouseNo = new javax.swing.JTextField();
        txtCommunity = new javax.swing.JTextField();
        txtCity = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        lblAge = new javax.swing.JLabel();
        txtAge = new javax.swing.JTextField();
        lblId = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        cmbBoxUpdate = new javax.swing.JComboBox<>();
        btnShow = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblHeading.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        lblHeading.setText("Person Information");
        add(lblHeading, new org.netbeans.lib.awtextra.AbsoluteConstraints(251, 6, -1, -1));

        lblPersonName.setText("Name:");
        add(lblPersonName, new org.netbeans.lib.awtextra.AbsoluteConstraints(248, 82, 65, -1));

        lblphone.setText("Phone:");
        add(lblphone, new org.netbeans.lib.awtextra.AbsoluteConstraints(248, 183, -1, -1));

        lblHeight.setText("Height:");
        add(lblHeight, new org.netbeans.lib.awtextra.AbsoluteConstraints(244, 227, -1, -1));

        lblWeight.setText("Weight:");
        add(lblWeight, new org.netbeans.lib.awtextra.AbsoluteConstraints(246, 271, -1, -1));

        lblHouseNo.setText("House No.:");
        add(lblHouseNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(223, 315, -1, -1));

        lblCommunity.setText("Community:");
        add(lblCommunity, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 359, -1, -1));

        lblCity.setText("City:");
        add(lblCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(264, 403, -1, -1));

        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });
        add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 77, 104, -1));

        txtPhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPhoneActionPerformed(evt);
            }
        });
        add(txtPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 178, 104, -1));

        txtHeight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHeightActionPerformed(evt);
            }
        });
        add(txtHeight, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 222, 104, -1));

        txtWeight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtWeightActionPerformed(evt);
            }
        });
        add(txtWeight, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 266, 104, -1));

        txtHouseNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHouseNoActionPerformed(evt);
            }
        });
        add(txtHouseNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 310, 104, -1));

        txtCommunity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCommunityActionPerformed(evt);
            }
        });
        add(txtCommunity, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 354, 104, -1));

        txtCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCityActionPerformed(evt);
            }
        });
        add(txtCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 398, 104, -1));

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(311, 456, -1, -1));

        lblAge.setText("Age:");
        add(lblAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(262, 149, -1, -1));

        txtAge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAgeActionPerformed(evt);
            }
        });
        add(txtAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 144, 104, -1));

        lblId.setText("Id:");
        add(lblId, new org.netbeans.lib.awtextra.AbsoluteConstraints(274, 122, -1, -1));

        txtId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdActionPerformed(evt);
            }
        });
        add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 112, 104, -1));

        add(cmbBoxUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(547, 78, -1, -1));

        btnShow.setText("Show");
        btnShow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowActionPerformed(evt);
            }
        });
        add(btnShow, new org.netbeans.lib.awtextra.AbsoluteConstraints(547, 144, -1, -1));

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(652, 144, -1, -1));

        jLabel1.setText("Id");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(562, 55, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    public void addDetails(){
        
        String Name = txtName.getText();
        int Id = Integer.parseInt(txtId.getText());
        int Age = Integer.parseInt(txtAge.getText());
        String Phone = txtPhone.getText();
        double Height = Double.parseDouble(txtHeight.getText());
        double Weight = Double.parseDouble(txtWeight.getText());
        int House_No = Integer.parseInt(txtHouseNo.getText());
        String Community_Name = txtCommunity.getText();
        String City = txtCity.getText();
        
        cmbBoxUpdate.addItem(String.valueOf(Id));
        Person pr = directory.addNewPersons();
        
        pr.setName(Name);
        pr.setId(Id);
        pr.setAge(Age);
        pr.setPhone(Phone);
        pr.setHeight(Height);
        pr.setWeight(Weight);
        pr.setHouse_No(House_No);
        pr.setCommunity_Name(Community_Name);
        pr.setCity_name(City);
    }
    public void populateComboBoxUpdate() {
        
        
        for( int i=0; i < directory.getDirectory().size(); i++){
             Person pr = new Person();
            
             pr = directory.getDirectory().get(i);
             String ID = String.valueOf(pr.getId());
             cmbBoxUpdate.addItem(ID);

          
        }
    }
    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void txtPhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPhoneActionPerformed

    private void txtHeightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHeightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHeightActionPerformed

    private void txtWeightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtWeightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtWeightActionPerformed

    private void txtHouseNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHouseNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHouseNoActionPerformed

    private void txtCommunityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCommunityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCommunityActionPerformed

    private void txtCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCityActionPerformed

    private void txtAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAgeActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        
        for (int i=0; i<directory.getDirectory().size(); i++) {
            
             Person pr = new Person();
             pr = directory.getDirectory().get(i);
            String ID1 = String.valueOf(pr.getId());
        
                if(ID1.equals(txtId.getText())){
                    JOptionPane.showMessageDialog(this, "This Id is already taken. Please select a new Id");
                    
                    return;
                }
        }
        
        if(txtName.getText().equals("")){
           
            JOptionPane.showMessageDialog(this, "Please Enter your Name");  
            
        
        }
         else if(txtId.getText().equals("")){
           
            JOptionPane.showMessageDialog(this, "Please Enter your Id");  
            
         }
         else if(txtAge.getText().equals("")){
           
            JOptionPane.showMessageDialog(this, "Please Enter your Age");  
            
         }
         
         else if(Integer.parseInt(txtAge.getText())> 200 ||Integer.parseInt(txtAge.getText())<0 ){
         
            JOptionPane.showMessageDialog(this, "Please enter a valid age");    
        }
         
         else if(txtPhone.getText().equals("")){
           
            JOptionPane.showMessageDialog(this, "Please Enter your Phone Number"); 
            
            
         }
         
         else if(Long.parseLong(txtPhone.getText()) < 99999999 ){
            
            JOptionPane.showMessageDialog(this, "Please enter a valid Phone Number");    
        }
         
         
         else if(txtHeight.getText().equals("")){
           
            JOptionPane.showMessageDialog(this, "Please Enter your Height");  
            
         }
         
         else if(Integer.parseInt(txtHeight.getText()) > 400 || Integer.parseInt(txtHeight.getText()) < 1 ){
            
            JOptionPane.showMessageDialog(this, "Are you an Alien. Please enter correct Height");    
        }
         
         else if(txtWeight.getText().equals("")){
           
            JOptionPane.showMessageDialog(this, "Please Enter your Weight");  
            
         }
          else if(Integer.parseInt(txtWeight.getText()) > 400 || Integer.parseInt(txtWeight.getText()) < 1 ||txtWeight.getText().equals("")){
            
            JOptionPane.showMessageDialog(this, "Are you an Alien. Please enter correct Weight");    
        }
       
         else if(txtHouseNo.getText().equals("")){
           
            JOptionPane.showMessageDialog(this, "Please Enter your House Number ");  
            
         }
          else if(txtCommunity.getText().equals("")){
           
            JOptionPane.showMessageDialog(this, "Please Enter Your Community Name");   
        
        }
        
       else if(txtCity.getText().equals("")){
           
            JOptionPane.showMessageDialog(this, "Please Enter your city of residence");   
        
        }
        
       else{
        addDetails();
        JOptionPane.showMessageDialog(this, "Personal details have been saved");
        
        
         emptyfields();
       }
         //populateComboBoxUpdate();
    }//GEN-LAST:event_btnSaveActionPerformed

    
    public void emptyfields(){
        txtName.setText("");
        txtId.setText("");
        txtAge.setText("");
        txtPhone.setText("");
        txtHeight.setText("");
        txtWeight.setText("");
        txtHouseNo.setText("");
        txtCommunity.setText("");
        txtCity.setText("");
        
    }
    private void txtIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdActionPerformed

    private void btnShowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowActionPerformed
        // TODO add your handling code here:
        for (int i=0; i<directory.getDirectory().size(); i++) {
            
             Person pr = new Person();
             pr = directory.getDirectory().get(i);
            
             String Name1 = String.valueOf(pr.getName());
             String ID1 = String.valueOf(pr.getId());
             String Age1 = String.valueOf(pr.getAge());
             String Phone1 = String.valueOf(pr.getPhone());
             String Height1 = String.valueOf(pr.getHeight());
             String Weight1 = String.valueOf(pr.getWeight());
             String HouseNo1 = String.valueOf(pr.getHouse_No());
             String Community1 = String.valueOf(pr.getCommunity_Name());
             String City1 = String.valueOf(pr.getCity_name());
//            String S[] = directory.getDirectory().get(i);

            if(cmbBoxUpdate.getSelectedItem() == null){
                
                
                JOptionPane.showMessageDialog(this, "Please select an Id");
            }
            else if(cmbBoxUpdate.getSelectedItem().equals(ID1)){
                
        txtName.setText(Name1);
        txtId.setText(ID1);
        txtAge.setText(Age1);
        txtPhone.setText(Phone1);
        txtHeight.setText(Height1);
        txtWeight.setText(Weight1);
        txtHouseNo.setText(HouseNo1);
        txtCommunity.setText(Community1);
        txtCity.setText(City1);
            }
        }
    }//GEN-LAST:event_btnShowActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        
        for (int i=0; i<directory.getDirectory().size(); i++) {
            
             Person pr = new Person();
             pr = directory.getDirectory().get(i);
            String ID1 = String.valueOf(pr.getId());
            
            
            if (ID1.equals(txtId.getText())){
                
                directory.getDirectory().remove(i);
              
                addDetails();
                emptyfields();
                
                
                
            }
        }
    }//GEN-LAST:event_btnUpdateActionPerformed
        

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnShow;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> cmbBoxUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblAge;
    private javax.swing.JLabel lblCity;
    private javax.swing.JLabel lblCommunity;
    private javax.swing.JLabel lblHeading;
    private javax.swing.JLabel lblHeight;
    private javax.swing.JLabel lblHouseNo;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblPersonName;
    private javax.swing.JLabel lblWeight;
    private javax.swing.JLabel lblphone;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtCity;
    private javax.swing.JTextField txtCommunity;
    private javax.swing.JTextField txtHeight;
    private javax.swing.JTextField txtHouseNo;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtWeight;
    // End of variables declaration//GEN-END:variables
}
