/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Ui;

import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import model.CarHistory;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import static javax.swing.text.html.HTML.Tag.OPTION;
import model.Car;

/**
 *
 * @author shubhampatil
 */
public class CreateJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateJPanel
     */
    CarHistory history;
    String Image;
     
    public CreateJPanel(CarHistory history) {
        initComponents();
        
        this.history = history;
    }

    /*CreateJPanel(CarHistory history) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
     /}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Title = new javax.swing.JLabel();
        labelBrand = new javax.swing.JLabel();
        labelModel = new javax.swing.JLabel();
        labelColour = new javax.swing.JLabel();
        labelYear = new javax.swing.JLabel();
        textBrand = new javax.swing.JTextField();
        textModel = new javax.swing.JTextField();
        textColour = new javax.swing.JTextField();
        textYear = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        labelEngine_no = new javax.swing.JLabel();
        textEngine_no = new javax.swing.JTextField();
        labelLicense_plate = new javax.swing.JLabel();
        textLicense_plate = new javax.swing.JTextField();
        labelSeats_no = new javax.swing.JLabel();
        labelOwner_name = new javax.swing.JLabel();
        labelOwner_tele_no = new javax.swing.JLabel();
        labelOwner_email_add = new javax.swing.JLabel();
        labelOwner_driv_lic = new javax.swing.JLabel();
        labelOwner_SSN = new javax.swing.JLabel();
        labelOwner_addr = new javax.swing.JLabel();
        labelService_rec = new javax.swing.JLabel();
        labelWarranty_year = new javax.swing.JLabel();
        textSeats_no = new javax.swing.JTextField();
        textOwner_name = new javax.swing.JTextField();
        textOwner_tele_no = new javax.swing.JTextField();
        textOwner_email_add = new javax.swing.JTextField();
        textOwner_driv_lic = new javax.swing.JTextField();
        textOwner_SSN = new javax.swing.JTextField();
        textOwner_addr = new javax.swing.JTextField();
        textService_rec = new javax.swing.JTextField();
        textWarranty_year = new javax.swing.JTextField();

        Title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Title.setText("CAR PROFILE");

        labelBrand.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelBrand.setText("Brand:");

        labelModel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelModel.setText("Model:");

        labelColour.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelColour.setText("Colour:");

        labelYear.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelYear.setText("Year:");

        textBrand.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        textBrand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textBrandActionPerformed(evt);
            }
        });

        textModel.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        textModel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textModelActionPerformed(evt);
            }
        });

        textColour.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        textColour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textColourActionPerformed(evt);
            }
        });

        textYear.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        textYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textYearActionPerformed(evt);
            }
        });

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        labelEngine_no.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelEngine_no.setText("Engine Number:");

        textEngine_no.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        textEngine_no.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textEngine_noActionPerformed(evt);
            }
        });

        labelLicense_plate.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelLicense_plate.setText("License_plate:");

        textLicense_plate.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        textLicense_plate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textLicense_plateActionPerformed(evt);
            }
        });

        labelSeats_no.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelSeats_no.setText("Seats Number:");

        labelOwner_name.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelOwner_name.setText("Owner Name:");

        labelOwner_tele_no.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelOwner_tele_no.setText("Owner Telephone Number:");

        labelOwner_email_add.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelOwner_email_add.setText("Owner Email Addresses:");

        labelOwner_driv_lic.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelOwner_driv_lic.setText("Owner Driver License:");

        labelOwner_SSN.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelOwner_SSN.setText("Owner Social Security Number:");

        labelOwner_addr.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelOwner_addr.setText("Owner Addresses:");

        labelService_rec.setText("Service Records:");

        labelWarranty_year.setText("Warranty Year:");

        textSeats_no.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        textSeats_no.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textSeats_noActionPerformed(evt);
            }
        });

        textOwner_name.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        textOwner_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textOwner_nameActionPerformed(evt);
            }
        });

        textOwner_tele_no.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        textOwner_email_add.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        textOwner_driv_lic.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        textOwner_SSN.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        textOwner_addr.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(Title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(86, 86, 86))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 292, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelModel, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelBrand, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelColour, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelYear, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelEngine_no)
                                    .addComponent(labelLicense_plate)
                                    .addComponent(labelSeats_no)
                                    .addComponent(labelOwner_name)
                                    .addComponent(labelOwner_tele_no)
                                    .addComponent(labelOwner_email_add)
                                    .addComponent(labelOwner_driv_lic)
                                    .addComponent(labelOwner_SSN)
                                    .addComponent(labelOwner_addr)
                                    .addComponent(labelService_rec)
                                    .addComponent(labelWarranty_year))
                                .addGap(113, 113, 113)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(textModel, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                                        .addComponent(textColour, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                                        .addComponent(textYear, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                                        .addComponent(textEngine_no)
                                        .addComponent(textLicense_plate)
                                        .addComponent(textSeats_no)
                                        .addComponent(textOwner_name)
                                        .addComponent(textOwner_tele_no, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(textOwner_email_add)
                                        .addComponent(textOwner_driv_lic)
                                        .addComponent(textOwner_SSN, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(textOwner_addr, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(textBrand))
                                    .addComponent(textService_rec, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(textWarranty_year, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(300, 300, 300))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(440, 440, 440))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(Title, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelBrand, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                    .addComponent(textBrand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelModel, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                    .addComponent(textModel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelColour, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                    .addComponent(textColour))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelYear, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                    .addComponent(textYear))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelEngine_no, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(textEngine_no))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelSeats_no, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(textSeats_no))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelLicense_plate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(textLicense_plate))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelOwner_name, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(textOwner_name))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelOwner_tele_no, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(textOwner_tele_no))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelOwner_email_add, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(textOwner_email_add))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelOwner_driv_lic, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(textOwner_driv_lic))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelOwner_SSN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(textOwner_SSN))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelOwner_addr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(textOwner_addr))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelService_rec)
                    .addComponent(textService_rec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelWarranty_year)
                    .addComponent(textWarranty_year, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(68, 68, 68)
                .addComponent(btnSave)
                .addGap(705, 705, 705))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void textBrandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textBrandActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textBrandActionPerformed

    private void textModelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textModelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textModelActionPerformed

    private void textColourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textColourActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textColourActionPerformed

    private void textYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textYearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textYearActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        
        if (textBrand.getText().equals("")||textModel.getText().equals("")||textColour.getText().equals("")||textYear.getText()==null||textEngine_no.getText()==null||textSeats_no.getText()==null||textLicense_plate.getText().equals("")||textOwner_name.getText().equals("")||textOwner_tele_no.getText().equals("")||textOwner_email_add.getText().equals("")||textOwner_driv_lic.getText().equals("")||textOwner_SSN.getText().equals("")||textOwner_addr.getText().equals("")||textService_rec.getText().equals("")||textWarranty_year.getText()==null) {
            JOptionPane.showMessageDialog(this, " Please fill all the empty field");
        }
        else if(!textOwner_email_add.getText().contains("@")||!textOwner_email_add.getText().contains(".")) {
            JOptionPane.showMessageDialog(this,"Enter a valid Email ID");
        }
        
        else {
      
        
        
        String Brand = textBrand.getText();
        String Model = textModel.getText();
        String Colour = textColour.getText();
        int Year = Integer.parseInt(textYear.getText());
        int Engine_no = Integer.parseInt(textEngine_no.getText());
        int Seats_no = Integer.parseInt(textSeats_no.getText());
        String License_plate = textLicense_plate.getText();
        String Owner_name = textOwner_name.getText();
        String Owner_tele_no = textOwner_tele_no.getText();
        String Owner_email_add = textOwner_email_add.getText();
        String Owner_driv_lic = textOwner_driv_lic.getText();
        String Owner_SSN = textOwner_SSN.getText();
        String Owner_addr = textOwner_addr.getText();
        String Service_rec = textService_rec.getText();
        int Warranty_year = Integer.parseInt(textWarranty_year.getText());
        
        Car cr = history.addNewCars();
        
        cr.setBrand(Brand);
        cr.setModel(Model);
        cr.setColour(Colour);
        cr.setYear(Year);
        cr.setEngine_no(Engine_no);
        cr.setSeats_no(Seats_no);
        cr.setLicense_plate(License_plate);
        cr.setOwner_name(Owner_name);
        cr.setOwner_tele_no(Owner_tele_no);
        cr.setOwner_email_add(Owner_email_add);
        cr.setOwner_driv_lic(Owner_driv_lic);
        cr.setOwner_SSN(Owner_SSN);
        cr.setOwner_addr(Owner_addr);
        cr.setService_rec(Service_rec);
        cr.setWarranty_year(Warranty_year);
        
        JOptionPane.showMessageDialog(this, "Car details have been saved");

        
        textBrand.setText("");
        textModel.setText("");
        textColour.setText("");
        textYear.setText("");
        textEngine_no.setText("");
        textSeats_no.setText("");
        textLicense_plate.setText("");
        textOwner_name.setText("");
        textOwner_tele_no.setText("");
        textOwner_email_add.setText("");
        textOwner_driv_lic.setText("");
        textOwner_SSN.setText("");
        textOwner_addr.setText("");
        textService_rec.setText("");
        textWarranty_year.setText(""); 
        
        
        
        
       /* car.setBrand(textBrand.getText());
        car.setModel(textModel.getText());
        car.setColour(textColour.getText());
        car.setYear(textYear.getText());
        car.setEngine_no(textEngine_no.getText());
        car.setSeats_no(textSeats_no.getText());
        car.setLicense_plate(textLicense_plate.getText());
        car.setOwner_name(textOwner_name.getText());
        car.setOwner_tele_no(textOwner_tele_no.getText());
        car.setOwner_email_add(textOwner_email_add.getText());
        car.setOwner_driv_lic(textOwner_driv_lic.getText());
        car.setOwner_SSN(textOwner_SSN.getText());
        car.setOwner_addr(textOwner_addr.getText());
        car.setService_rec(textService_rec.getText());
        car.setWarranty_year(textWarranty_year.getText());
        
        */
        }
        
    }//GEN-LAST:event_btnSaveActionPerformed

    private void textEngine_noActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textEngine_noActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textEngine_noActionPerformed

    private void textLicense_plateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textLicense_plateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textLicense_plateActionPerformed

    private void textSeats_noActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textSeats_noActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textSeats_noActionPerformed

    private void textOwner_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textOwner_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textOwner_nameActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Title;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel labelBrand;
    private javax.swing.JLabel labelColour;
    private javax.swing.JLabel labelEngine_no;
    private javax.swing.JLabel labelLicense_plate;
    private javax.swing.JLabel labelModel;
    private javax.swing.JLabel labelOwner_SSN;
    private javax.swing.JLabel labelOwner_addr;
    private javax.swing.JLabel labelOwner_driv_lic;
    private javax.swing.JLabel labelOwner_email_add;
    private javax.swing.JLabel labelOwner_name;
    private javax.swing.JLabel labelOwner_tele_no;
    private javax.swing.JLabel labelSeats_no;
    private javax.swing.JLabel labelService_rec;
    private javax.swing.JLabel labelWarranty_year;
    private javax.swing.JLabel labelYear;
    private javax.swing.JTextField textBrand;
    private javax.swing.JTextField textColour;
    private javax.swing.JTextField textEngine_no;
    private javax.swing.JTextField textLicense_plate;
    private javax.swing.JTextField textModel;
    private javax.swing.JTextField textOwner_SSN;
    private javax.swing.JTextField textOwner_addr;
    private javax.swing.JTextField textOwner_driv_lic;
    private javax.swing.JTextField textOwner_email_add;
    private javax.swing.JTextField textOwner_name;
    private javax.swing.JTextField textOwner_tele_no;
    private javax.swing.JTextField textSeats_no;
    private javax.swing.JTextField textService_rec;
    private javax.swing.JTextField textWarranty_year;
    private javax.swing.JTextField textYear;
    // End of variables declaration//GEN-END:variables
}
